### ISSUE TITLE
Problem with 'Unable to load FFProbe'

### ISSUE THREAD

**Issue by kawaiipeace** [pascalbaljetmedia/laravel-ffmpeg#87]
Greeting, I have a problem with this 'Unable to load FFProbe'
I want to convert from all audio to .flac and my controller's just like this
public function conversion(StoreAudioRequest $request)
```
   {
        $audio = Audio::create([
            'disk'          => 'audios_disk',
            'original_name' => $request->audio->getClientOriginalName(),
            'path'          => $request->audio->store('audios', 'audios_disk'),
            //'title'         => $request->title,
        ]);

        $this->dispatch(new ConvertAudioForDownloading($audio));

        return response()->json([
            'id' => $audio->id,
        ], 201);
    }
```
Then run in `$this->dispatch(new ConvertAudioForDownloading($audio));` its throw to
public function handle()
```
      {
          $lowBitrateFormat = (new Flac)->setAudioKiloBitrate(16);
          FFMpeg::fromDisk($this->audio->disk)
              ->open($this->audio->path)
              ->export()
              ->toDisk('downloadable_audios')
              ->inFormat($lowBitrateFormat)
              ->save($this->audio->id . '.flac');
          $this->audio->update([
              'converted_for_downloading_at' => Carbon::now(),
          ]);
      }
```
and Laravel call the error in  `FFMpeg::fromDisk($this->audio->disk)`.
I followed with your old issue about this problem liked this [https://github.com/pascalbaljetmedia/laravel-ffmpeg/issues/73](url)
Can't solve this problem at all. 
What should I do? Thank you very much.

Ps. I've set filesystems.php liked
```
   'disks' => [
        'audios_disk' => [
            'driver' => 'local',
            'root' => public_path('uploads'),
        ],
    ],
```

**Comment by pascalbaljet** [comment]
How are the sources encoded? You probably have a FFMpeg build that has no support for Flac encoding.

**Comment by kawaiipeace** [comment]
I used .wav and .mp3 files to convert. First I created the web page for upload audio files (which supported extension of .mpga, .wav and so on). The file that upload is completely but get problem which can't Unable to load FFProbe.
Now I tried to change from Flac encoding to Mp3 and get the same issue.

**Comment by pascalbaljet** [comment]
Did you set the correct paths in the config file? Where is ```ffprobe``` located?

**Comment by codiiv** [comment]
@pascalbaljet I think you should add more documentation in the readme file  about the locations of the files depending on the user's OS. I fought with this issue for a bit as well.

**Comment by kawaiipeace** [comment]
@pascalbaljet According to the in vendor directory (pbmedia/laravel-ffmpeg/config/laravel-ffmpeg.php)
I just set path like this
```
return [
    'default_disk' => 'local',

    'ffmpeg.binaries' => env('FFMPEG_BINARIES','ffmpeg'),
    'ffmpeg.threads'  => 12,

    'ffprobe.binaries' => env('FFPROBE_BINARIES','ffprobe'),

    'timeout' => 3600,
];
```
But it's not worked.

**Comment by codiiv** [comment]
@kawaiipeace I think you are editing it in the wrong place: 

1) First,  run  `php artisan vendor:publish --provider="Pbmedia\LaravelFFMpeg\FFMpegServiceProvider"`
That will create **laravel-ffmpeg.php** in the  **config**  folder   ( **/config/laravel-ffmpeg.php** )
2) Change  ffmpeg  and ffprobe  binaries   paths  to : 
```
'ffmpeg.binaries' => '/usr/bin/ffmpeg',   

'ffprobe.binaries' => '/usr/bin/ffprobe',
```

**Comment by kawaiipeace** [comment]
Thank you, everyone.  The problem has been solved.
I run XAMPP in Windows and confusing about setting the ffmpeg and ffprobe path in Windows
the path is
```
'ffmpeg.binaries'  => 'C:/FFmpeg/bin/ffmpeg.exe',
'ffprobe.binaries' => 'C:/FFmpeg/bin/ffprobe.exe',
```
Lastly, I forget to install core FFMPEG for Windows on my PC.  I think it's can run without this.
It's all my fault and thank you everyone.

**Comment by chisumo2016** [comment]
The issue isn't solved on my side . Kindly assist

return [
    'default_disk' => 'local',

    'ffmpeg' => [
       // 'binaries' => env('FFMPEG_BINARIES', 'ffmpeg'),
        'ffmpeg.binaries'  => 'C:/FFmpeg/bin/ffmpeg.exe',
        'threads' => 12,
    ],

    'ffprobe' => [
        //'binaries' => env('FFPROBE_BINARIES', 'ffprobe'),
        'ffprobe.binaries' => 'C:/FFmpeg/bin/ffprobe.exe',


    ],

**Comment by vishaldobariya** [comment]
<?php

return [
    'default_disk' => 'local',

    'ffmpeg.binaries' => '/usr/local/bin/ffmpeg',
    'ffmpeg.threads'  => 12,

    'ffprobe.binaries' => '/usr/local/bin/ffprobe',

    'timeout' => 3600,
];
It's works on local but what we have to set on hosting because it's display unable to load FFProbe Please give me your feedback/suggestions

**Comment by legionlad** [comment]
Here, how i solved it.

For me it was rather un-related. 

I was using SpatieMedia with ffmpeg to clip a video, store it in a temp folder then save .webm in the same directory created by spatiemedia.

The Ffprobe was loading right, it was the hard-coded paths in spatie-media which were wrong.

Fix
vendor\spatie\laravel-medialibrary\config\media-library.php 
 Changed those line to this, on my server Ubuntu 20
   
---------- 

    'ffmpeg_path' => '/usr/bin/ffmpeg',
        'ffprobe_path' =>  '/usr/bin/ffprobe',

----------


vendor\spatie\laravel-medialibrary\src\Conversions\ImageGenerators\Video.php
 Same change in convert() function

----------
 

      $ffmpeg = FFMpeg::create([
                'ffmpeg.binaries' => '/usr/bin/ffmpeg',
                'ffprobe.binaries' => '/usr/bin/ffprobe',
        ]);
----------
